schema = 3

[mod]
  [mod."github.com/chromedp/cdproto"]
    version = "v0.0.0-20240801214329-3f85d328b335"
    hash = "sha256-vPQ9ux/CZdQx77nJU4MklvRm2N1Wa2Q9swsw0MX/VhY="
  [mod."github.com/chromedp/chromedp"]
    version = "v0.10.0"
    hash = "sha256-buhjjUAAKZ7yNdHTnDGntPN5EpMQpfonMZGPRBqdMu0="
  [mod."github.com/chromedp/sysutil"]
    version = "v1.0.0"
    hash = "sha256-q0D6shGNtlM1EDiSXiysOSj+GKXerywCDHy6bV+Hn20="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.4.0"
    hash = "sha256-I3BWBluCakfFuTKkwi5Dh+DlzpdcizOAxa4lKOUo8Ak="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."golang.org/x/sys"]
    version = "v0.23.0"
    hash = "sha256-tC6QVLu72bADgINz26FUGdmYqKgsU45bHPg7sa0ZV7w="
