schema = 3

[mod]
  [mod."github.com/chromedp/cdproto"]
    version = "v0.0.0-20230208104036-c3c870aa4771"
    hash = "sha256-fFNBwHayYo+T4jMKN6NrnmHyw7TOcWNaLRc6/04Xp4E="
  [mod."github.com/chromedp/chromedp"]
    version = "v0.8.7"
    hash = "sha256-3PaT/RPMgi8+XBSxDEukQ7l8mtT1lCuRnKCzOyEfHZw="
  [mod."github.com/chromedp/sysutil"]
    version = "v1.0.0"
    hash = "sha256-q0D6shGNtlM1EDiSXiysOSj+GKXerywCDHy6bV+Hn20="
  [mod."github.com/gobwas/httphead"]
    version = "v0.1.0"
    hash = "sha256-6wFni/JkK2GqtVs3IW+GxHRNoSu4EJfzaBRGX2hF1IA="
  [mod."github.com/gobwas/pool"]
    version = "v0.2.1"
    hash = "sha256-py8/+Wo5Q83EbYMUKK5U/4scRcyMo2MjOoxqi5y+sUY="
  [mod."github.com/gobwas/ws"]
    version = "v1.1.0"
    hash = "sha256-acKk+P+NtXvrOaT6WhJzI6RLUeB1ejITtGjqabx74pg="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."golang.org/x/sys"]
    version = "v0.5.0"
    hash = "sha256-0LTr3KeJ1OMQAwYUQo1513dXJtQAJn5Dq8sFkc8ps1U="
